### ISSUE TITLE
Combine historical congressional election results with Daily Kos 2016 

### ISSUE THREAD

**Issue by gati** [Data4Democracy/just-politics#2]
The Election Transparency project compiled a list of county-level congressional results dating back to 1980, up to 2014. https://data.world/data4democracy/election-transparency/file/HouseElectionResults1980to2014.csv

Daily Kos has election congressional election results for 2016 https://docs.google.com/spreadsheets/d/1oRl7vxEJUUDWJCyrjo62cELJD2ONIVl-D9TSUKiK9jk/edit#gid=1163624377

We'd like to combine these two datasets so we have consistent county-level results through 2016.

**Comment by tejasdessai** [comment]
I'm on this @gati

**Comment by gati** [comment]
Awesome! Thanks @tejasdessai!

**Comment by tejasdessai** [comment]
@gati this is done. 
I've stayed consistent with Election transparency format. Some information is missing though - such as month, state_fips, G and L votes. Daily Kos does not provide this information so we might have to use some other sources to fill in the missing values. 

[merged data v1.0.xlsx](https://github.com/Data4Democracy/just-politics/files/985662/merged.data.v1.0.xlsx)

**Comment by gati** [comment]
Awesome! Thanks @tejasdessai for jumping on that so quickly. Do you have a data.world account? I can give you contributor access to the dataset we set up (https://data.world/data4democracy/just-politics) so all the files we're creating get stashed in the same place. :)

**Comment by tejasdessai** [comment]
Yes @gati I am https://data.world/tejasdessai

**Comment by gati** [comment]
Awesome! Thanks, just made you a contributor
